spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dogs
    username: postgres
    password: changeit
  flyway:
    url: jdbc:postgresql://localhost:5432/dogs
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-version: 1.0.0
    baseline-on-migrate: true


app:
  api:
    dog-breed:
      host: https://dog.ceo/api/breed
      images:
        by-master-breed-path: /{masterBreed}/images/random
        by-master-and-sub-breed-path: /{masterBreed}/{subBreed}/images/random
